# Generated by Django 6.0.3 on 2026-03-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_num_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cedula de extranjeria')], max_length=2),
        ),
    ]
