# Generated by Django 6.0.3 on 2026-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_num_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_codigo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
