# Generated by Django 6.0.3 on 2026-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_reset_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_codigo_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
