# Generated by Django 6.0.3 on 2026-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_reset_codigo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_intentos',
            field=models.IntegerField(default=0),
        ),
    ]
